# Set prefix
unbind C-b
set -g  prefix C-a
bind C-a send-prefix



# Split panes using v and h
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'


# Mouse scroll enters copy mode automatically
set -g mouse on

# Alt+Up enters copy mode and pages up in one keystroke
# bind -n M-Up copy-mode \; send-keys -X page-up

# Alt+arrows for navigation inside copy mode
# bind -T copy-mode M-Up send-keys -X page-up
# bind -T copy-mode M-Down send-keys -X page-down

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
